//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace knt5
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.Web;

    public partial class Object
    {
        public int oId { get; set; }
        [DisplayName("物資名稱")]
        public string oName { get; set; }
        [DisplayName("物資照片")]
        public string oPhoto { get; set; }
        public HttpPostedFileBase photo { get; set; }

        [DisplayName("需求數量")]
        public string oNumber { get; set; }
        [DisplayName("需求說明")]
        public string oIntro { get; set; }
        [DisplayName("物資類別")]
        public string type { get; set; }
    }
}
